# Generated by Django 5.2.6 on 2025-11-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchlistDb',
        ),
    ]
