# Generated by Django 5.2.8 on 2026-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
