# Generated by Django 5.2.8 on 2026-01-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_watchlist_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
